### ISSUE TITLE
Annotation: GeneNames hinzufügen

### ISSUE THREAD

**Issue by easelpeasel** [easelpeasel/galaxy_450k#11]
GeneName kann noch nicht hinzugefügt werden, hier müsste die AffymetrixAnnotation eingefügt werden, die wir auch schon in den ExpressionsDaten verwenden.

**Comment by easelpeasel** [comment]
Mach mal noch ein Beispiel passend dazu

UCSC RefGene Name (e.g. "SFRS11;LRRC40"):

Gene Name:

Glaub der Bezeichner aus der Wikipedia passt hier nciht ganz.

**Comment by sblid** [comment]
Welche cg's haben versch. Gene zugeordnet?

**Comment by sblid** [comment]
temp2 = c()
for(ii in 1:nrow(inputdata)){
  print(ii)
  symbols = inputdata[ii,]$GeneSymbol
  split = symbols
  if(nchar(symbols) > 0){
    if(regexpr(";", symbols) > 0){
      split = strsplit(symbols, ";")[[1]][[1]]
    }
  }
  temp2 = append(temp2, split)
}

ändern mit sub(';.*', '', your_text)

**Comment by sblid** [comment]
Gleiches Gen für alle Beispiele im Infotext nehmen

**Comment by easelpeasel** [comment]
Erledigt.
