### ISSUE TITLE
Extract: Funnorm failes

### ISSUE THREAD

**Issue by sblid** [easelpeasel/galaxy_450k#38]
Von einem mset das mit preprocessFunctional() normalisiert wurde können keine Werte extrahiert werden. 

------------------------------------------------------------------------------

The following objects are masked from 'package:Biobase':

    anyMissing, rowMedians

Error in .local(object, ...) : unused argument (type = "")
Calls: getM -> getM -> .local

------------------------------------------------------------------------------

The following objects are masked from 'package:Biobase':

    anyMissing, rowMedians

Error in .local(object, ...) : 
  unused arguments (offset = 100, betaThreshold = 0)
Calls: getBeta -> getBeta -> .local

**Comment by easelpeasel** [comment]
Erledigt. Funnorm und Quantile haben ein GemocRatioSet zurückgegeben, und hier wird Beta bzw. M nicht neu berechnet, entsprechend sind OffSet, etc. als Parameter nicht notwendig.
